### ISSUE TITLE
[prometheus-to-sd] Error while sending request to Stackdriver googleapi: Error 400: One or more TimeSeries could not be written

### ISSUE THREAD

**Issue by myyra** [GoogleCloudPlatform/k8s-stackdriver#308]
Getting this error in the logs every minute. Starts appearing few minutes after the cluster creation.

Here's the full output:

```
Error while sending request to Stackdriver googleapi: Error 400: One or more TimeSeries could not be written: Unknown metric: kubernetes.io/internal/addons/workload_identity/go_gc_duration_seconds_count: timeSeries[31]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_gc_duration_seconds_sum: timeSeries[40]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_goroutines: timeSeries[33]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_info: timeSeries[5]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_alloc_bytes: timeSeries[7]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_alloc_bytes_total: timeSeries[18]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_buck_hash_sys_bytes: timeSeries[53]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_frees_total: timeSeries[46]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_gc_cpu_fraction: timeSeries[10]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_gc_sys_bytes: timeSeries[51]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_heap_alloc_bytes: timeSeries[50]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_heap_idle_bytes: timeSeries[4]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_heap_inuse_bytes: timeSeries[54]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_heap_objects: timeSeries[43]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_heap_released_bytes: timeSeries[49]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_heap_sys_bytes: timeSeries[6]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_last_gc_time_seconds: timeSeries[55]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_lookups_total: timeSeries[56]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_mallocs_total: timeSeries[20]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_mcache_inuse_bytes: timeSeries[52]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_mcache_sys_bytes: timeSeries[19]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_mspan_inuse_bytes: timeSeries[44]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_mspan_sys_bytes: timeSeries[17]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_next_gc_bytes: timeSeries[48]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_other_sys_bytes: timeSeries[35]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_stack_inuse_bytes: timeSeries[39]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_stack_sys_bytes: timeSeries[45]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_memstats_sys_bytes: timeSeries[34]; Unknown metric: kubernetes.io/internal/addons/workload_identity/go_threads: timeSeries[41]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_cpu_seconds_total: timeSeries[1]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_max_fds: timeSeries[32]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_open_fds: timeSeries[47]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_resident_memory_bytes: timeSeries[42]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_start_time_seconds: timeSeries[3]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_virtual_memory_bytes: timeSeries[30]; Unknown metric: kubernetes.io/internal/addons/workload_identity/process_virtual_memory_max_bytes: timeSeries[38]; Unknown metric: kubernetes.io/internal/addons/workload_identity/promhttp_metric_handler_requests_in_flight: timeSeries[2]; Unknown metric: kubernetes.io/internal/addons/workload_identity/promhttp_metric_handler_requests_total: timeSeries[27-29]; Value type for metric kubernetes.io/internal/addons/workload_identity/metadata_server_build_info must be DOUBLE, but is INT64.: timeSeries[0], badRequest
```

`source: "stackdriver.go:60" `

This is the GKE cluster config I'm using:
```
{
  "cluster": {
    "name": "test-cluster",
    "masterAuth": {
      "clientCertificateConfig": {}
    },
    "network": "projects/REDACTED/global/networks/default",
    "addonsConfig": {
      "httpLoadBalancing": {
        "disabled": true
      },
      "horizontalPodAutoscaling": {},
      "kubernetesDashboard": {
        "disabled": true
      },
      "networkPolicyConfig": {},
      "istioConfig": {
        "disabled": true
      }
    },
    "subnetwork": "projects/REDACTED/regions/europe-west4/subnetworks/default",
    "nodePools": [
      {
        "name": "default-pool",
        "config": {
          "machineType": "g1-small",
          "diskSizeGb": 10,
          "oauthScopes": [
            "https://www.googleapis.com/auth/devstorage.read_only",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring",
            "https://www.googleapis.com/auth/servicecontrol",
            "https://www.googleapis.com/auth/service.management.readonly",
            "https://www.googleapis.com/auth/trace.append"
          ],
          "metadata": {
            "disable-legacy-endpoints": "true"
          },
          "imageType": "COS",
          "diskType": "pd-standard",
          "shieldedInstanceConfig": {
            "enableSecureBoot": true,
            "enableIntegrityMonitoring": true
          }
        },
        "initialNodeCount": 2,
        "autoscaling": {},
        "management": {
          "autoUpgrade": true,
          "autoRepair": true
        },
        "version": "1.15.8-gke.2",
        "upgradeSettings": {
          "maxSurge": 1
        }
      }
    ],
    "networkPolicy": {
      "provider": "CALICO",
      "enabled": true
    },
    "ipAllocationPolicy": {
      "useIpAliases": true
    },
    "masterAuthorizedNetworksConfig": {},
    "defaultMaxPodsConstraint": {
      "maxPodsPerNode": "110"
    },
    "authenticatorGroupsConfig": {},
    "privateClusterConfig": {},
    "databaseEncryption": {
      "keyName": "projects/REDACTED/locations/europe-west4/keyRings/REDACTED",
      "state": "ENCRYPTED"
    },
    "shieldedNodes": {
      "enabled": true
    },
    "workloadIdentityConfig": {
      "identityNamespace": "REDACTED"
    },
    "clusterTelemetry": {
      "type": "ENABLED"
    },
    "initialClusterVersion": "1.15.8-gke.2",
    "location": "europe-west4-a"
  }
}
```

**Comment by daveio** [comment]
bump; same thing happening in my cluster.

**Comment by tonybenchsci** [comment]
Same here `1.14.10-gke.27 `

**Comment by drazul** [comment]
Same error. 
The installed version of prometheus-to-sd was v0.8.2 and I upgraded it to v0.9.2, but it still throwing same error.

**Comment by bibekmantree** [comment]
I get 403:


E0714 13:56:20.343486       1 stackdriver.go:58] Error while sending request to Stackdriver googleapi: Error 403: Permission monitoring.timeSeries.create denied (or the resource may not exist)., forbidden

**Comment by mxhofer** [comment]
Same here with `1.14.10-gke.36`

**Comment by peterldowns** [comment]
Experiencing this with `1.16.13-gke.1`

**Comment by hermanbanken** [comment]
Happening for us on:
- 1.15.12-gke.13
- 1.15.12-gke.16

**Comment by hermanbanken** [comment]
StackOverflow question about this:
https://stackoverflow.com/questions/63167757/gcp-logging-k8s-error-while-sending-request-to-stackdriver-googleapi-error-4

Seems like it was fixed in 1.15.12-gke.3, but for us it broken on 1.15.12-gke.16.

Maybe the problem is not the version, but the fact that we upgraded an existing cluster to enable the Workload Identity addon.

**Comment by chribsen** [comment]
Also happening for us on `1.15.12-gke.20`

**Comment by chribsen** [comment]
Does this bug only affect shipment of a particular metric?

**Comment by nicoleczhu** [comment]
FYI: This is happening for me on 1.16.401, i.e. the latest stable/default gke release

**Comment by loburm** [comment]
Hi Everyone,
First I'm really sorry for a such long response. Somehow this bug was lost in our queue.

1. Initial bug that contained a lot of errors messages about nonexisting metrics have been fixed, starting from 1.15.9-gke.10.
2. We still have an issue with metadata_server_build_info on 1.15.0-gke.10. I have created internal bug to fix metric type. Most probably issue will be fixed in internal configuration and will not require any cluster upgrade.
3. On 1.16 there are additional issue with loading_cache_fetch_count and loading_cache_latency metrics. I think it will be fixed simultaneously  with second issue.
4. In one comment I see that someone have been receiving error 403. Please verify that:

- Monitoring API is enabled in your project.
- Service Account attached to your nodes have a permission to write metrics.

**Comment by JEndler** [comment]
Hi there,

Unsure if this is the right place to ask, but i'll give it a shot.

Im currently using [prometheus-to-sd](https://github.com/GoogleCloudPlatform/k8s-stackdriver/tree/master/prometheus-to-sd) as a sidecar container and running into the 403 permission error.

Specifically the error is: 
`Error while sending request to Stackdriver googleapi: Error 403: Permission monitoring.timeSeries.create denied (or the resource may not exist)., forbidden`
I've verified that both the Monitoring API is enabled and the Service Account does have the role *role: roles/monitoring.metricWriter*.

This is the yaml im using to deploy it:

```yaml
- name: prometheus-to-sd
    image: gcr.io/google-containers/prometheus-to-sd:v0.9.0
    ports:
      - name: profiler
        containerPort: 6060
      - name: debug
        containerPort: 16061
    command:
      - /monitor
      - --stackdriver-prefix=custom.googleapis.com
      - --source=clickhouse-pod:http://localhost:8001/metrics
      - --pod-id=$(POD_NAME)
      - --namespace-id=$(POD_NAMESPACE)
    env:
      - name: POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
```

Theres also another instance of this exact container running, scraping some other metrics, thats working just fine with the same service account (and running in the same node pool).

Does anyone have an idea of what might be the issue here?
